name = "Lava"
uuid = "d1a8d690-f7c2-11e9-320a-9fe20c683921"
authors = ["gcmiao <gc@roastew.com>"]
version = "0.1.0"

[deps]
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
VulkanCore = "16167f82-ea26-5cba-b1de-ed6fd5e30a11"
